services:
  - type: web
    name: collabbridge-api
    env: node
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: collabbridge-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FIREBASE_PROJECT_ID
        value: collabbridge-2c528
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      # Redis URL for caching - connects to the Redis service below
      - key: REDIS_URL
        fromService:
          type: redis
          name: collabbridge-redis
          property: connectionString

databases:
  - name: collabbridge-db
    databaseName: collabbridge
    user: collabbridge_user

# Redis service for caching
- type: redis
  name: collabbridge-redis
  ipAllowList: []
